### ISSUE TITLE
LICs dependant on Point.angleBetween do not work if points are stacked on top of each other

### ISSUE THREAD

**Issue by ntomsic** [agnesforsberg/Decide#35]
For example LIC1 with the input 
`Point(0, 15), Point(0, 15), Point(0, -11)`
will always be false since oRadius will be `NaN`

Do we want to fix this or just assume that two radar blips can not be on top of each other since they would be indistinguishable from a single blip?

**Comment by ntomsic** [comment]
@Cawibo What are your thoughts on this?

**Comment by cawibo** [comment]
:hmm:

Hadn't thought of that, but it kind of makes sense for the angle between the same Point to be NaN, no?

The definition for LIC6 mentions identical points, so I guess the system can deliver blips on top of each other? Not sure if it makes sense in a real-world setting though.

**Comment by cawibo** [comment]
```
 boolean pointsCoincide = (a.equals(b) || b.equals(c) || c.equals(a));

/*
 * if two or more points coincide or if the points make an obtuse triangle, then
 * the longest distance between any two points make the diameter of the smallest
 * encompassing circle.
 */
if (pointsCoincide || a.angleBetween(b, c) > Math.PI / 2 || b.angleBetween(a, c) > Math.PI / 2
        || c.angleBetween(a, b) > Math.PI / 2) {
    oRadius = DoubleStream.of(a.distanceTo(b), b.distanceTo(c), c.distanceTo(a)).max().getAsDouble() / 2;
}
```

Would this be an acceptable fix to the bug?

**Comment by cawibo** [comment]
bump @ntomsic

**Comment by ntomsic** [comment]
Yeah i think so! Nice work :) Do we want to add `pointsCoincide` to all LICs that include circles then?

**Comment by ntomsic** [comment]
Im thinking we might want to make a new function that calculates the smallest circle given three points as well, there is quite a bit of redundant code at the moment, LICs 1,8 and 13 all reuse the same parts

**Comment by cawibo** [comment]
That sounds like a plan. I can look into it after work.
